### PR TITLE
Adding in a starter kubernetes file for vault

### PR DESCRIPTION
**Pull request by dgreeninger**
A first pass at getting some info from the kubernetes cluster. 
Checking for helm chart configuration and the passed values.

### CODE REVIEW

**Comment by roooms** [comment]
Hey @dgreeninger thanks very much for contributing this. We are re-evaluating the next release of hcdiag-ext and reducing the scope of checks while we address some regulatory and privacy requirements. I'll leave this open for now and hope to review and merge in future.

**Comment by ml4** [comment]
Hello @roooms is this PR still valid given recent merges?

**Comment by roooms** [comment]
Will leave this open and reconsider in a future hcdiag-ext release. For now everything we need can be pulled from the Vault API, so the environment configuration isn't necessary.

**Comment by roooms** [comment]
Following a review of the software purpose, we will not be adding this functionality to hcdiag-ext.

**Pull request closed without merging**
